;; Transport
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

;; ============ Trunk from/to PBX ============

[pbx-trunk]
type=endpoint
context=from-pbx
disallow=all
allow=ulaw
aors=pbx-trunk-aor
direct_media=no

[pbx-trunk-aor]
type=aor
contact=sip:asterisk-pbx:5060

[pbx-trunk-identify]
type=identify
endpoint=pbx-trunk
match=10.99.0.10/32
